/* eslint-disable prettier/prettier */
// const textIds = [
//   'tt7991608',
//   'tt4244994',
//   'tt2397461',
//   'tt2953050',
//   'tt9376612',
//   // tt11214590  House of Gucci
//   // tt10293406  The Power of the Dog
//   // tt10872600  Spider-Man: No Way Home
//   // tt4244994   The Last Duel
//   // tt4513678   Ghostbusters: Afterlife
//   // tt1160419    Dune
//   // tt7991608    Red Notice
//   // tt8721424    tick, tick...BOOM!
//   // tt10838180   The Matrix Resurrections
//   // tt9376612    Shang-Chi and the Legend of the Ten Rings
//   // tt2382320    No Time to Die
//   // tt7097896    Venom: Let There Be Carnage
//   // tt13070602   A Castle for Christmas
//   // tt6920084    Resident Evil: Welcome to Raccoon City
//   // tt10187208   A Boy Called Christmas

//   // tt0111161   The Shawshank Redemption
//   // tt0133093   The Matrix
//   // tt0068646   The Godfather
// ];
const recList = [
    {title: 'Wonder Woman 1984', year: '2020', imdb_id: 'tt7126948'},
    {
      title: 'Deathstroke: Knights & Dragons - The Movie',
      year: '2020',
      imdb_id: 'tt12876132',
    },
    {title: 'Honest Thief', year: '2020', imdb_id: 'tt1838556'},
    {title: 'Fatman', year: '2020', imdb_id: 'tt10310140'},
    {title: 'Jiu Jitsu', year: '2020', imdb_id: 'tt9624766'},
    {title: 'Copper Bill', year: '2020', imdb_id: 'tt10529644'},
    {title: 'Chick Fight', year: '2020', imdb_id: 'tt10944486'},
    {title: 'The Dalton Gang', year: '2020', imdb_id: 'tt11902980'},
    {title: 'Vanguard', year: '2020', imdb_id: 'tt9695722'},
    {title: 'Monsters of Man', year: '2020', imdb_id: 'tt6456326'},
    {
      title: 'Rogue Warfare: Death of a Nation',
      year: '2020',
      imdb_id: 'tt7983744',
    },
    {title: 'Unfortunate Stories', year: '2020', imdb_id: 'tt11362866'},
    {title: 'Hard Kill', year: '2020', imdb_id: 'tt11656172'},
    {title: 'Welcome to Sudden Death', year: '2020', imdb_id: 'tt10804786'},
    {
      title: 'Arthur & Merlin: Knights of Camelot',
      year: '2020',
      imdb_id: 'tt7052270',
    },
    {title: 'Christmas Crossfire', year: '2020', imdb_id: 'tt13446424'},
    {title: "Roald Dahl's The Witches", year: '2020', imdb_id: 'tt0805647'},
    {
      title: 'Demon Slayer the Movie: Mugen Train',
      year: '2020',
      imdb_id: 'tt11032374',
    },
    {title: 'The Craft: Legacy', year: '2020', imdb_id: 'tt4685762'},
    {
      title: 'American Pie Presents: Girls Rules',
      year: '2020',
      imdb_id: 'tt11771594',
    },
  ];
  const upcomingMovies = [
    {imdb_id: 'tt10838180', release: '2021-12-16', title: 'The Matrix 4'},
    {imdb_id: 'tt6856242', release: '2021-12-22', title: "The King's Man"},
    {imdb_id: 'tt1262426', release: '2021-12-22', title: 'Wicked'},
    {
      imdb_id: 'tt10872600',
      release: '2021-12-17',
      title: 'Spider-Man: No Way Home',
    },
    {imdb_id: 'tt11703710', release: '2021-12-22', title: 'Downton Abbey 2'},
    {imdb_id: 'tt2094116', release: '2021-12-23', title: 'Sherlock Holmes 3'},
    {imdb_id: 'tt0995854', release: '2021-12-22', title: 'A Journal for Jordan'},
    {imdb_id: 'tt12889404', release: '2022-01-06', title: 'Cyrano'},
    {imdb_id: 'tt10028196', release: '2021-12-25', title: 'Laal Singh Chaddha'},
  ];
  
  const recommendation = [
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BZjVmYzVjZWUtODE3NS00ZTExLThhMTUtNzU3ZGE2NGYwOWE4XkEyXkFqcGdeQXVyMTAwODc1OTcy._V1_.jpg',
      gen: [
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
        {genre: 'Thriller', id: 14},
        {genre: 'Horror', id: 28},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BZjVmYzVjZWUtODE3NS00ZTExLThhMTUtNzU3ZGE2NGYwOWE4XkEyXkFqcGdeQXVyMTAwODc1OTcy._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt7097896',
      keywords: [
        {id: 58, keyword: 'marvel comics'},
        {id: 62, keyword: 'superhero'},
        {id: 63, keyword: 'based on comic'},
        {id: 81, keyword: 'sequel'},
        {id: 785, keyword: 'second part'},
      ],
      more_like_this: {},
      plot: "Plot unknown. Sequel to the 2018 film 'Venom'.",
      popularity: 143,
      rating: 0,
      release: null,
      title: 'Venom: Let There Be Carnage',
      trailer: 'https://www.youtube.com/embed/-V0ARqmnzSk',
      type: 'movie',
      year: 2021,
    },
    {
      countries: ['China', 'United States of America'],
      description: 'Sequel to the box-office hit film "Venom."',
      directors: ['Andy Serkis'],
      genres: ['Action', 'Sci-Fi', 'Superhero', 'Horror'],
      imdb_id: 'tt7097896',
      imdb_rating: '7.76316',
      language: ['English'],
      popularity: '137',
      rated: null,
      release_date: '2021-09-15',
      runtime: 90,
      stars: [
        'Tom Hardy',
        'Woody Harrelson',
        'Michelle Williams',
        'Reid Scott',
        'Naomie Harris',
        'Stephen Graham',
        'Tom Holland',
        'J.K. Simmons',
        'Amber Sienna',
      ],
      status: 'OK',
      status_message: 'Query was successful',
      tagline: null,
      title: 'Venom: Let There Be Carnage',
      vote_count: '38',
      year: '2021',
      youtube_trailer_key: '-ezfi6FQ8Ds',
    },
  ];
  
  const BestMovie = [
    {
      adult: false,
      backdrop_path: '/70nxSw3mFBsGmtkvcs91PbjerwD.jpg',
      genre_ids: [878, 28, 12],
      id: 580489,
      original_language: 'en',
      original_title: 'Venom: Let There Be Carnage',
      overview:
        'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
      popularity: 7534.804,
      poster_path:
        'https://image.tmdb.org/t/p/w500/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
      release_date: '2021',
      title: 'Venom: Let There Be Carnage',
      video: false,
      vote_average: 7.2,
      vote_count: 4337,
    },
    {
      adult: false,
      backdrop_path: '/5uVhMGsps81CN0S4U9NF0Z4tytG.jpg',
      genre_ids: [28, 35, 80, 53],
      id: 512195,
      original_language: 'en',
      original_title: 'Red Notice',
      overview:
        "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
      popularity: 4173.995,
      poster_path:
        'https://image.tmdb.org/t/p/w500/wdE6ewaKZHr62bLqCn7A2DiGShm.jpg',
      release_date: '2021',
      title: 'Red Notice',
      video: false,
      vote_average: 6.8,
      vote_count: 1931,
    },
    {
      adult: false,
      backdrop_path: '/mFbS5TwN95BcSEfiztdchLgTQ0v.jpg',
      genre_ids: [28, 18, 36],
      id: 617653,
      original_language: 'en',
      original_title: 'The Last Duel',
      overview:
        'King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.',
      popularity: 2824.034,
      poster_path:
        'https://image.tmdb.org/t/p/w500/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg',
      release_date: '2021',
      title: 'The Last Duel',
      video: false,
      vote_average: 7.6,
      vote_count: 841,
    },
    {
      adult: false,
      backdrop_path: '/zBkHCpLmHjW2uVURs5uZkaVmgKR.jpg',
      genre_ids: [16, 35, 10751],
      id: 585245,
      original_language: 'en',
      original_title: 'Clifford the Big Red Dog',
      overview:
        'As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.',
      popularity: 2960.577,
      poster_path:
        'https://image.tmdb.org/t/p/w500/ygPTrycbMSFDc5zUpy4K5ZZtQSC.jpg',
      release_date: '2021',
      title: 'Clifford the Big Red Dog',
      video: false,
      vote_average: 7.5,
      vote_count: 509,
    },
    {
      adult: false,
      backdrop_path: '/g2djzUqA6mFplzC03gDk0WSyg99.jpg',
      genre_ids: [12, 16, 35, 10751, 14, 10402],
      id: 568124,
      original_language: 'en',
      original_title: 'Encanto',
      overview:
        "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
      popularity: 2782.527,
      poster_path:
        'https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg',
      release_date: '2021',
      title: 'Encanto',
      video: false,
      vote_average: 7.4,
      vote_count: 295,
    },
    {
      adult: false,
      backdrop_path: '/cinER0ESG0eJ49kXlExM0MEWGxW.jpg',
      genre_ids: [28, 12, 14],
      id: 566525,
      original_language: 'en',
      original_title: 'Shang-Chi and the Legend of the Ten Rings',
      overview:
        'Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.',
      popularity: 2712.063,
      poster_path:
        'https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg',
      release_date: '2021',
      title: 'Shang-Chi and the Legend of the Ten Rings',
      video: false,
      vote_average: 7.8,
      vote_count: 4158,
    },
    {
      adult: false,
      backdrop_path: '/iUeeZ5PWfZGgUtCJfwcgmCfdzoI.jpg',
      genre_ids: [16, 878, 10751, 35],
      id: 482321,
      original_language: 'en',
      original_title: "Ron's Gone Wrong",
      overview:
        "In a world where walking, talking, digitally connected bots have become children's best friends, an 11-year-old finds that his robot buddy doesn't quite work the same as the others do.",
      popularity: 2508.588,
      poster_path:
        'https://image.tmdb.org/t/p/w500/gA9QxSravC2EVEkEKgyEmDrfL0e.jpg',
      release_date: '2021',
      title: "Ron's Gone Wrong",
      video: false,
      vote_average: 8.5,
      vote_count: 309,
    },
    {
      adult: false,
      backdrop_path: '/VlHt27nCqOuTnuX6bku8QZapzO.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      popularity: 2376.947,
      poster_path:
        'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      release_date: '2021',
      title: 'Spider-Man: No Way Home',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg',
      genre_ids: [18, 36, 12],
      id: 589761,
      original_language: 'ru',
      original_title: 'Чернобыль',
      overview:
        'The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.',
      popularity: 2078.543,
      poster_path:
        'https://image.tmdb.org/t/p/w500/kfQJQWFEoWRVBH8FUKnT0HX1yRS.jpg',
      release_date: '2021',
      title: 'Chernobyl: Abyss',
      video: false,
      vote_average: 6.3,
      vote_count: 234,
    },
    {
      adult: false,
      backdrop_path: '/dnxrremCrghG7z97zDeGPNrl75A.jpg',
      genre_ids: [12, 28, 53],
      id: 370172,
      original_language: 'en',
      original_title: 'No Time to Die',
      overview:
        'Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
      popularity: 1742.817,
      poster_path:
        'https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg',
      release_date: '2021',
      title: 'No Time to Die',
      video: false,
      vote_average: 7.6,
      vote_count: 2488,
    },
    {
      adult: false,
      backdrop_path: '/lyvszvJJqqI8aqBJ70XzdCNoK0y.jpg',
      genre_ids: [28, 12, 14, 878],
      id: 524434,
      original_language: 'en',
      original_title: 'Eternals',
      overview:
        'The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.',
      popularity: 1392.582,
      poster_path:
        'https://image.tmdb.org/t/p/w500/6AdXwFTRTAzggD2QUTt5B7JFGKL.jpg',
      release_date: '2021',
      title: 'Eternals',
      video: false,
      vote_average: 7.1,
      vote_count: 1398,
    },
    {
      adult: false,
      backdrop_path: '/oE6bhqqVFyIECtBzqIuvh6JdaB5.jpg',
      genre_ids: [878, 18, 12],
      id: 522402,
      original_language: 'en',
      original_title: 'Finch',
      overview:
        "On a post-apocalyptic Earth, a robot, built to protect the life of his dying creator's beloved dog, learns about life, love, friendship, and what it means to be human.",
      popularity: 1223.679,
      poster_path:
        'https://image.tmdb.org/t/p/w500/jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg',
      release_date: '2021',
      title: 'Finch',
      video: false,
      vote_average: 8.2,
      vote_count: 1402,
    },
    {
      adult: false,
      backdrop_path: '/1zgob2Z8xVE3RZUgOKnHKcVPzOE.jpg',
      genre_ids: [16, 35, 14],
      id: 877183,
      original_language: 'en',
      original_title: 'The Simpsons in Plusaversary',
      overview:
        "The Simpsons host a Disney+ Day party and everyone is on the list… except Homer. With friends from across the service and music fit for a Disney Princess, Plusaversary is Springfield's event of the year.",
      popularity: 1100.97,
      poster_path:
        'https://image.tmdb.org/t/p/w500/9xaAT3V3I9xxqnNiEjCivNFfdlh.jpg',
      release_date: '2021',
      title: 'The Simpsons in Plusaversary',
      video: false,
      vote_average: 6.7,
      vote_count: 151,
    },
    {
      adult: false,
      backdrop_path: '/uWGPC7j70LE64nbetxQGSSYJO53.jpg',
      genre_ids: [53, 10752],
      id: 762433,
      original_language: 'en',
      original_title: 'Zeros and Ones',
      overview:
        "Called to Rome to stop an imminent terrorist bombing, a soldier desperately seeks news of his imprisoned brother — a rebel with knowledge that could thwart the attack. Navigating the capital's darkened streets, he races to a series of ominous encounters to keep the Vatican from being blown to bits.",
      popularity: 1082.027,
      poster_path:
        'https://image.tmdb.org/t/p/w500/a6balsDWCFMHPaPT6rFoBpNjR6z.jpg',
      release_date: '2021',
      title: 'Zeros and Ones',
      video: false,
      vote_average: 5.6,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
      genre_ids: [35, 28, 12, 878],
      id: 550988,
      original_language: 'en',
      original_title: 'Free Guy',
      overview:
        'A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.',
      popularity: 1022.319,
      poster_path:
        'https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg',
      release_date: '2021',
      title: 'Free Guy',
      video: false,
      vote_average: 7.8,
      vote_count: 4042,
    },
    {
      adult: false,
      backdrop_path: '/h3HsfV8Kn9Sz2QWUYYdP5ya23hx.jpg',
      genre_ids: [878, 12],
      id: 438631,
      original_language: 'en',
      original_title: 'Dune',
      overview:
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
      popularity: 1049.741,
      poster_path:
        'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
      release_date: '2021',
      title: 'Dune',
      video: false,
      vote_average: 8,
      vote_count: 4671,
    },
    {
      adult: false,
      backdrop_path: '/vJ3ED2jPblACDqaJPZlbN6T1yjy.jpg',
      genre_ids: [53, 80, 28, 12],
      id: 776821,
      original_language: 'es',
      original_title: 'Las leyes de la frontera',
      overview:
        "Introverted Girona student Nacho meets two delinquents from the city's Chinatown and gets caught up in a summer onslaught of burglaries and hold ups that will change his life.",
      popularity: 968.573,
      poster_path:
        'https://image.tmdb.org/t/p/w500/qrq7sGXraFM6H9OcHFKQTKe8A3f.jpg',
      release_date: '2021',
      title: 'Outlaws',
      video: false,
      vote_average: 6.8,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: '/4EJSMQOM1bZPHvzqAQe87suBxdf.jpg',
      genre_ids: [10752, 36, 18],
      id: 885110,
      original_language: 'en',
      original_title: 'Amina',
      overview:
        "In 16th-century Zazzau, now Zaria, Nigeria, Amina must utilize her military skills and tactics to defend her family's kingdom. Based on a true story.",
      popularity: 979.431,
      poster_path:
        'https://image.tmdb.org/t/p/w500/gII53HAH7UA1yx189vROMzWA5ib.jpg',
      release_date: '2021',
      title: 'Amina',
      video: false,
      vote_average: 6.3,
      vote_count: 55,
    },
    {
      adult: false,
      backdrop_path: '/7h5WAPAcUzOWpp2jrwHBB48790j.jpg',
      genre_ids: [16, 28],
      id: 843241,
      original_language: 'ja',
      original_title: '劇場版 七つの大罪 光に呪われし者たち',
      overview:
        'With the help of the "Dragon Sin of Wrath" Meliodas and the worst rebels in history, the Seven Deadly Sins, the "Holy War", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the "Lion Sin of Pride" Escanor\'s life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.',
      popularity: 917.966,
      poster_path:
        'https://image.tmdb.org/t/p/w500/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg',
      release_date: '2021',
      title: 'The Seven Deadly Sins: Cursed by Light',
      video: false,
      vote_average: 8.1,
      vote_count: 244,
    },
  ];
  
  const mojje = [
    {
      banner: 'https://image.tmdb.org/t/p/w500//AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg',
      description: 'A continuation of Spider-Man Far From Home',
      directors: [
        'David H. Venghaus Jr.',
        'Brian Avery Galligan',
        'Jon Watts',
        'George Cottle',
      ],
      gen: [
        {genre: 'Adventure', id: 4},
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
      ],
      image_url:
        'https://image.tmdb.org/t/p/w500//1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
      imdb_id: 'tt10872600',
      imdb_rating: '7.25',
      keywords: [
        {id: 57, keyword: 'marvel cinematic universe'},
        {id: 58, keyword: 'marvel comics'},
        {id: 62, keyword: 'superhero'},
        {id: 63, keyword: 'based on comic'},
        {id: 81, keyword: 'sequel'},
      ],
      language: ['English'],
      plot: 'A continuation of Spider-Man Far From Home',
      popularity: 32,
      rated: 'Action,  Adventure,  Sci-Fi     ',
      rating: 0,
      release: '2021-12-17',
      stars: [
        'Tom Holland',
        'Zendaya',
        'Benedict Cumberbatch',
        'Marisa Tomei',
        'J.K. Simmons',
        'Jamie Foxx',
        'Alfred Molina',
        'Jacob Batalon',
        'Tony Revolori',
        'Angourie Rice',
        'Hannibal Buress',
        'Harry Holland',
        'Arian Moayed',
        'Andrew Garfield',
        'Kirsten Dunst',
        'Jon Favreau',
        'Michael Keaton',
        'Michael Mando',
        'Bokeem Woodbine',
        'Stephen Graham',
        'Tom Hardy',
        'Jared Leto',
        'Charlie Cox',
        'Nikolaj Coster-Waldau',
      ],
      tagline: '',
      title: 'Spider-Man: No Way Home',
      trailer: 'https://www.youtube.com/embed/pBvH8hvnJPk',
      type: 'movie',
      vote_count: '24',
      year: 2021,
    },
    {
      banner: 'https://image.tmdb.org/t/p/w500//5uVhMGsps81CN0S4U9NF0Z4tytG.jpg',
      description:
        "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
      directors: ['James Bitonti', 'Rawson Marshall Thurber'],
      gen: [
        {genre: 'Crime', id: 7},
        {genre: 'Comedy', id: 9},
        {genre: 'Action', id: 13},
        {genre: 'Thriller', id: 14},
      ],
      image_url:
        'https://image.tmdb.org/t/p/w500//q2d56YvJ3s9W73lqrk16Nzcc7xD.jpg',
      imdb_id: 'tt7991608',
      imdb_rating: '6.625',
      keywords: [
        {id: 1402, keyword: 'money'},
        {id: 2964, keyword: 'art'},
        {id: 2965, keyword: 'thief'},
        {id: 2966, keyword: 'agent'},
        {id: 2967, keyword: 'wanted'},
      ],
      language: ['English'],
      plot: "An Interpol agent tracks the world's most wanted art thief.",
      popularity: 1040,
      rated: null,
      rating: 0,
      release: null,
      stars: [
        'Dwayne Johnson',
        'Ryan Reynolds',
        'Gal Gadot',
        'Ritu Arya',
        'Chris Diamantopoulos',
        'Steve Eifert',
        'Melissa Kennemore',
        'Ivan Mbakop',
        'Christopher Cocke',
        'Evan A. Dunn',
        'Rafael Petardi',
        'Jeramie Julian',
        'Tom Choi',
      ],
      tagline: "They're as dangerous as they come.",
      title: 'Red Notice',
      trailer: 'https://www.youtube.com/embed/Pj0wz7zu3Ms',
      type: 'movie',
      vote_count: '8',
      year: 2021,
    },
    {
      banner: 'https://image.tmdb.org/t/p/w500//mFbS5TwN95BcSEfiztdchLgTQ0v.jpg',
      description:
        'King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.',
      directors: ['Ridley Scott'],
      gen: [{genre: 'Drama', id: 8}],
      image_url:
        'https://image.tmdb.org/t/p/w500//zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg',
      imdb_id: 'tt4244994',
      imdb_rating: '7',
      keywords: [
        {id: 1878, keyword: 'three word title'},
        {id: 2842, keyword: 'written by star'},
      ],
      language: ['English'],
      plot: 'King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.',
      popularity: 2021,
      rated: null,
      rating: 0,
      release: '2021-10-14',
      stars: [
        'Jodie Comer',
        'Matt Damon',
        'Adam Driver',
        'Ben Affleck',
        'Harriet Walter',
        'Nathaniel Parker',
        'Michael McElhatton',
        'Alex Lawther',
        'Zoé Bruneau',
        'Ian Pirie',
        'Sam Hazeldine',
        'Brian F. Mulvey',
        "Caoimhe O'Malley",
        'Zeljko Ivanek',
      ],
      tagline: null,
      title: 'The Last Duel',
      trailer: 'https://www.youtube.com/embed/mgygUwPJvYk',
      type: 'movie',
      vote_count: '2',
      year: 2021,
    },
    {
      banner: 'https://image.tmdb.org/t/p/w500//dB0CxRwLXJoOrRPUvsJjb2hnPtq.jpg',
      description:
        'A continuation of the story established in the first MATRIX film, reuniting cinematic icons Neo & Trinity as they venture back into the Matrix and even deeper down the rabbit hole. A mind-bending new adventure with action and epic scale, it’s set in a familiar yet even more provocative world where reality is more subjective than ever and all that’s required to see the truth is to free your mind.',
      directors: ['Lana Wachowski'],
      gen: [
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
      ],
      image_url:
        'https://image.tmdb.org/t/p/w500//xLNtaLaHudIzOqdEZ7R3lcDLrQQ.jpg',
      imdb_id: 'tt10838180',
      imdb_rating: '7.4',
      keywords: [
        {id: 81, keyword: 'sequel'},
        {id: 688, keyword: 'fourth part'},
      ],
      language: ['English'],
      plot: 'The plot is currently unknown.',
      popularity: 99,
      rated: null,
      rating: 0,
      release: '2021-12-16',
      stars: [
        'Keanu Reeves',
        'Carrie-Anne Moss',
        'Yahya Abdul-Mateen II',
        'Jonathan Groff',
        'Jessica Henwick',
        'Neil Patrick Harris',
        'Priyanka Chopra',
        'Lambert Wilson',
        'Jada Pinkett Smith',
        'Daniel Bernhardt',
        'Christina Ricci',
        'Ellen Hollman',
        'Brian J. Smith',
        'Toby Onwumere',
        'Eréndira Ibarra',
        'Andrew Lewis Caldwell',
        'Max Riemelt',
        'Telma Hopkins',
        'Chris Reid',
        'Ian Pirie',
        'Etienne Vick',
        'Mel Powell',
        'Andrew Koponen',
        'James D. Weston II',
        'John Lobato',
        'Thomas Dalby',
        'Clayton Watson',
        'Stephen Dunlevy',
        'Tiger Hu Chen',
      ],
      tagline: 'The choice is yours.',
      title: 'The Matrix 4',
      trailer: 'https://www.youtube.com/embed/nNpvWBuTfrc',
      type: 'movie',
      vote_count: '25',
      year: 2021,
    },
  ];
  
  const sairam = [
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BMTk3ZGM2YzQtMmYxYy00NDZjLWFmOTUtZTQwMzg0ZjA5ZjU3XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_.jpg',
      description:
        'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
      directors: 'Cary Joji Fukunaga',
      gen: [
        {genre: 'Adventure', id: 4},
        {genre: 'Action', id: 13},
        {genre: 'Thriller', id: 14},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BMTk3ZGM2YzQtMmYxYy00NDZjLWFmOTUtZTQwMzg0ZjA5ZjU3XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt2382320',
      imdb_rating: '7.5',
      keywords: [
        {id: 480, keyword: 'troubled production'},
        {id: 900, keyword: 'jamaica'},
        {id: 901, keyword: 'miss moneypenny character'},
        {id: 902, keyword: 'q character'},
        {id: 903, keyword: 'official james bond series'},
      ],
      language: 'English, French, Italian, Russian, Spanish, German',
      plot: 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
      popularity: 116,
      poster:
        'https://m.media-amazon.com/images/M/MV5BYWQ2NzQ1NjktMzNkNS00MGY1LTgwMmMtYTllYTI5YzNmMmE0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 0,
      release: '2021-09-30',
      stars: 'Daniel Craig, Ana de Armas, Rami Malek',
      title: 'No Time to Die',
      trailer: 'https://www.youtube.com/embed/BIhNsAtPbPI',
      type: 'movie',
      vote_count: '235,365',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BNTMxOGI4OGMtMTgwMy00NmFjLWIyOTUtYjQ0OGQ4Mjk0YjNjXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg',
      description:
        "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
      directors: 'Jon Watts',
      gen: [
        {genre: 'Adventure', id: 4},
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BNTMxOGI4OGMtMTgwMy00NmFjLWIyOTUtYjQ0OGQ4Mjk0YjNjXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt10872600',
      imdb_rating: 'N/A',
      keywords: [
        {id: 57, keyword: 'marvel cinematic universe'},
        {id: 58, keyword: 'marvel comics'},
        {id: 62, keyword: 'superhero'},
        {id: 63, keyword: 'based on comic'},
        {id: 81, keyword: 'sequel'},
      ],
      language: 'English',
      plot: 'A continuation of Spider-Man Far From Home',
      popularity: 32,
      poster:
        'https://m.media-amazon.com/images/M/MV5BMDUzNWJhZWQtYzU3Zi00M2NjLThjZjEtMTRmMjRmNzBmMWI2XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_SX300.jpg',
      rated: 'N/A',
      rating: 0,
      release: '2021-12-17',
      stars: 'Zendaya, Benedict Cumberbatch, Tom Holland',
      title: 'Spider-Man: No Way Home',
      trailer: 'https://www.youtube.com/embed/N6wMMMt5DY4',
      type: 'movie',
      vote_count: 'N/A',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BYTlhNzJjYzYtNGU3My00ZDI5LTgzZDUtYzllYjU1ZmU0YTgwXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_.jpg',
      description:
        'Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.',
      directors: 'Patty Jenkins',
      gen: [
        {genre: 'Adventure', id: 4},
        {genre: 'Fantasy', id: 6},
        {genre: 'Action', id: 13},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BYTlhNzJjYzYtNGU3My00ZDI5LTgzZDUtYzllYjU1ZmU0YTgwXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt7126948',
      imdb_rating: '5.4',
      keywords: [
        {id: 22, keyword: 'dc comics'},
        {id: 62, keyword: 'superhero'},
        {id: 81, keyword: 'sequel'},
        {id: 171, keyword: 'dc extended universe'},
        {id: 499, keyword: 'action heroine'},
      ],
      language: 'English, Arabic, Russian, Mandarin',
      plot: 'Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.',
      popularity: 26,
      poster:
        'https://m.media-amazon.com/images/M/MV5BYTlhNzJjYzYtNGU3My00ZDI5LTgzZDUtYzllYjU1ZmU0YTgwXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 5.4,
      release: '2021-03-31',
      stars: 'Gal Gadot, Chris Pine, Kristen Wiig',
      title: 'Wonder Woman 1984',
      trailer: 'https://www.youtube.com/embed/vNUcjqP11OY',
      type: 'movie',
      vote_count: '238,147',
      year: 2021,
    },
    {
      banner: 'aa.com',
      description:
        'King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.',
      directors: 'Ridley Scott',
      gen: [{genre: 'Drama', id: 8}],
      image_url: 'aa.com',
      imdb_id: 'tt4244994',
      imdb_rating: '7.7',
      keywords: [
        {id: 1878, keyword: 'three word title'},
        {id: 2842, keyword: 'written by star'},
      ],
      language: 'English, German',
      plot: 'King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire by challenging him to a duel.',
      popularity: 2021,
      poster:
        'https://m.media-amazon.com/images/M/MV5BZGExZTUzYWQtYWJjZi00OTI4LTk4OGYtNTA2YzcwMmNiZTMxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
      rated: 'R',
      rating: 0,
      release: '2021-10-14',
      stars: 'Matt Damon, Adam Driver, Jodie Comer',
      title: 'The Last Duel',
      trailer: 'https://www.youtube.com/embed/QqUI0Uxn0JY',
      type: 'movie',
      vote_count: '23,192',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BMGZmOGJjYjYtMWFkZi00NTE2LTk5NjktOGZiNDM2ZjBiMjk5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
      description:
        'When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.',
      directors: 'Jason Reitman',
      gen: [
        {genre: 'Fantasy', id: 6},
        {genre: 'Comedy', id: 9},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BMGZmOGJjYjYtMWFkZi00NTE2LTk5NjktOGZiNDM2ZjBiMjk5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt4513678',
      imdb_rating: '7.6',
      keywords: [
        {id: 78, keyword: 'ghostbuster'},
        {id: 79, keyword: 'ghostbusters'},
        {id: 80, keyword: 'psychotronic film'},
        {id: 81, keyword: 'sequel'},
        {id: 82, keyword: 'third part'},
      ],
      language: 'English',
      plot: 'When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.',
      popularity: 281,
      poster:
        'https://m.media-amazon.com/images/M/MV5BMmZiMjdlN2UtYzdiZS00YjgxLTgyZGMtYzE4ZGU5NTlkNjhhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 0,
      release: '2021-11-11',
      stars: 'Carrie Coon, Paul Rudd, Finn Wolfhard',
      title: 'Ghostbusters: Afterlife',
      trailer: 'https://www.youtube.com/embed/ahZFCF--uRY',
      type: 'movie',
      vote_count: '42,333',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BMGFkZGY0NTgtMGEyZC00YzhjLTkyOWItYzMzOTljMDA3ZjU2XkEyXkFqcGdeQXVyNzc4NTU3Njg@._V1_.jpg',
      description:
        "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.",
      directors: 'Denis Villeneuve',
      gen: [
        {genre: 'Adventure', id: 4},
        {genre: 'Drama', id: 8},
        {genre: 'Sci-Fi', id: 11},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BMGFkZGY0NTgtMGEyZC00YzhjLTkyOWItYzMzOTljMDA3ZjU2XkEyXkFqcGdeQXVyNzc4NTU3Njg@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt1160419',
      imdb_rating: '8.2',
      keywords: [
        {id: 5, keyword: 'based on novel'},
        {id: 99, keyword: 'dune'},
        {id: 100, keyword: 'feudalism'},
        {id: 101, keyword: 'adaptation'},
        {id: 102, keyword: 'desert'},
      ],
      language: 'English, Mandarin',
      plot: "Feature adaptation of Frank Herbert's science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.",
      popularity: 44,
      poster:
        'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 0,
      release: '2021-09-30',
      stars: 'Timothée Chalamet, Rebecca Ferguson, Zendaya',
      title: 'Dune',
      trailer: 'https://www.youtube.com/embed/hOy_UYSJWLQ',
      type: 'movie',
      vote_count: '383,442',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BOWQ2MWRiMTItNTk2ZC00MDc1LWI1ZTMtMTBjODU4YmU3YzIzXkEyXkFqcGdeQXVyNzU3NjUxMzE@._V1_.jpg',
      description: "An Interpol agent tracks the world's most wanted art thief.",
      directors: 'Rawson Marshall Thurber',
      gen: [
        {genre: 'Crime', id: 7},
        {genre: 'Comedy', id: 9},
        {genre: 'Action', id: 13},
        {genre: 'Thriller', id: 14},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BOWQ2MWRiMTItNTk2ZC00MDc1LWI1ZTMtMTBjODU4YmU3YzIzXkEyXkFqcGdeQXVyNzU3NjUxMzE@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt7991608',
      imdb_rating: '6.4',
      keywords: [
        {id: 1402, keyword: 'money'},
        {id: 2964, keyword: 'art'},
        {id: 2965, keyword: 'thief'},
        {id: 2966, keyword: 'agent'},
        {id: 2967, keyword: 'wanted'},
      ],
      language: 'English',
      plot: "An Interpol agent tracks the world's most wanted art thief.",
      popularity: 1040,
      poster:
        'https://m.media-amazon.com/images/M/MV5BZmRjODgyMzEtMzIxYS00OWY2LTk4YjUtMGMzZjMzMTZiN2Q0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 0,
      release: null,
      stars: 'Dwayne Johnson, Ryan Reynolds, Gal Gadot',
      title: 'Red Notice',
      trailer: 'https://www.youtube.com/embed/hRuUB6RKExQ',
      type: 'movie',
      vote_count: '70,263',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BN2I5NzlmMWYtYjIwYy00Y2ZiLWI0ODgtYjAxNDZiZGJlMjlhXkEyXkFqcGdeQXVyMzk1MDQ2MQ@@._V1_.jpg',
      description: 'The plot is currently unknown.',
      directors: 'Lana Wachowski',
      gen: [
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BN2I5NzlmMWYtYjIwYy00Y2ZiLWI0ODgtYjAxNDZiZGJlMjlhXkEyXkFqcGdeQXVyMzk1MDQ2MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt10838180',
      imdb_rating: 'N/A',
      keywords: [
        {id: 81, keyword: 'sequel'},
        {id: 688, keyword: 'fourth part'},
      ],
      language: 'English',
      plot: 'The plot is currently unknown.',
      popularity: 99,
      poster:
        'https://m.media-amazon.com/images/M/MV5BMGJkNDJlZWUtOGM1Ny00YjNkLThiM2QtY2ZjMzQxMTIxNWNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
      rated: 'R',
      rating: 0,
      release: '2021-12-16',
      stars: 'Keanu Reeves, Christina Ricci, Carrie-Anne Moss',
      title: 'The Matrix 4',
      trailer: 'https://www.youtube.com/embed/MldbRLuzGnI',
      type: 'movie',
      vote_count: 'N/A',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BYzM0YjJlMWEtZTg0MS00NjM4LWJkMDktN2VmZGU2ZjQ1YjI2XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg',
      description:
        'Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.',
      directors: 'Destin Daniel Cretton',
      gen: [
        {genre: 'Adventure', id: 4},
        {genre: 'Fantasy', id: 6},
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BYzM0YjJlMWEtZTg0MS00NjM4LWJkMDktN2VmZGU2ZjQ1YjI2XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt9376612',
      imdb_rating: '7.5',
      keywords: [
        {id: 58, keyword: 'marvel comics'},
        {id: 59, keyword: 'based on comic book'},
        {id: 62, keyword: 'superhero'},
        {id: 63, keyword: 'based on comic'},
        {id: 695, keyword: 'martial arts'},
      ],
      language: 'English, Mandarin',
      plot: "The movie, based on Marvel Comics, will focus on Shang-Chi; 'The Master of Kung-Fu'.",
      popularity: 3,
      poster:
        'https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 0,
      release: null,
      stars: 'Simu Liu, Awkwafina, Tony Chiu-Wai Leung',
      title: 'Shang-Chi and the Legend of the Ten Rings',
      trailer: 'https://www.youtube.com/embed/jSnc8Mt_EEI',
      type: 'movie',
      vote_count: '243,232',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BZjVmYzVjZWUtODE3NS00ZTExLThhMTUtNzU3ZGE2NGYwOWE4XkEyXkFqcGdeQXVyMTAwODc1OTcy._V1_.jpg',
      description:
        'Eddie Brock attempts to reignite his career by interviewing serial killer Cletus Kasady, who becomes the host of the symbiote Carnage and escapes prison after a failed execution.',
      directors: 'Andy Serkis',
      gen: [
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
        {genre: 'Thriller', id: 14},
        {genre: 'Horror', id: 28},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BZjVmYzVjZWUtODE3NS00ZTExLThhMTUtNzU3ZGE2NGYwOWE4XkEyXkFqcGdeQXVyMTAwODc1OTcy._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt7097896',
      imdb_rating: '6.3',
      keywords: [
        {id: 58, keyword: 'marvel comics'},
        {id: 62, keyword: 'superhero'},
        {id: 63, keyword: 'based on comic'},
        {id: 81, keyword: 'sequel'},
        {id: 785, keyword: 'second part'},
      ],
      language: 'English',
      plot: "Plot unknown. Sequel to the 2018 film 'Venom'.",
      popularity: 143,
      poster:
        'https://m.media-amazon.com/images/M/MV5BYTc3ZTAwYTgtMmM4ZS00MDRiLWI2Y2EtYmRiZmE0YjkzMGY1XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg',
      rated: 'PG-13',
      rating: 0,
      release: null,
      stars: 'Tom Hardy, Woody Harrelson, Michelle Williams',
      title: 'Venom: Let There Be Carnage',
      trailer: 'https://www.youtube.com/embed/-V0ARqmnzSk',
      type: 'movie',
      vote_count: '69,425',
      year: 2021,
    },
    {
      banner:
        'https://m.media-amazon.com/images/M/MV5BNDJlNmJjZDYtMWRjZS00ZDQwLTk3NzUtNGQwM2ZhZTg0YjViXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg',
      description:
        'Set in 1998, this origin story explores the secrets of the mysterious Spencer Mansion and the ill-fated Raccoon City.',
      directors: 'Johannes Roberts',
      gen: [
        {genre: 'Sci-Fi', id: 11},
        {genre: 'Action', id: 13},
        {genre: 'Mystery', id: 15},
        {genre: 'Horror', id: 28},
      ],
      image_url:
        'https://m.media-amazon.com/images/M/MV5BNDJlNmJjZDYtMWRjZS00ZDQwLTk3NzUtNGQwM2ZhZTg0YjViXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX182_CR0,0,182,268_AL_.jpg',
      imdb_id: 'tt6920084',
      imdb_rating: '5.6',
      keywords: [
        {id: 129, keyword: 'based on video game'},
        {id: 418, keyword: 'reboot'},
        {id: 429, keyword: 'zombie'},
        {id: 1946, keyword: 'reboot of series'},
        {id: 2743, keyword: 're boot'},
      ],
      language: 'English',
      plot: "Set in 1998, this 'Resident Evil' origin story explains the secrets of the Spencer Mansion and Raccoon City.",
      popularity: 271,
      poster:
        'https://m.media-amazon.com/images/M/MV5BNjRmMDUxODctYjg3NC00NDRhLWJhZWItMjg0OTZkMDBjNWUxXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg',
      rated: 'R',
      rating: 0,
      release: null,
      stars: 'Kaya Scodelario, Robbie Amell, Hannah John-Kamen',
      title: 'Resident Evil: Welcome to Raccoon City',
      trailer: 'https://www.youtube.com/embed/e3KzJWcmE7g',
      type: 'movie',
      vote_count: '2,579',
      year: 2021,
    },
  ];
  
  export {recList, BestMovie, recommendation, mojje, sairam};
  